---
before_install:
  # Install pandoc
  - sudo apt-get update
  - sudo apt-get -y install pandoc
  - pandoc --version

script:
  # create docs directory for pandoc output
  - mkdir docs
  - mkdir docs/edgy-joke
  - mkdir docs/how-i-got-here
  - mkdir docs/media
  - mkdir docs/edgy-joke/media/
  - mkdir docs/how-i-got-here/media/
  - cp edgy-joke/media/* docs/edgy-joke/media/
  - cp how-i-got-here/media/* docs/how-i-got-here/media/
  # Generate reveal.js powered HTML from Markdown
  - pandoc --standalone -t revealjs -o docs/edgy-joke/index.html edgy-joke/slides.md -V revealjs-url='https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.9.2' -V theme=solarized
  - pandoc  --standalone -t revealjs  -o docs/how-i-got-here/index.html how-i-got-here/slides.md -V revealjs-url='https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.9.2' -V theme=moon

# Deploy to GitHub pages (see https://docs.travis-ci.com/user/deployment/pages/)
deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
