---
before_install:
  # Install pandoc
  - sudo apt-get update
  - sudo apt-get -y install pandoc
  - pandoc --version

script:
  # create docs directory for pandoc output
  - mkdir docs
  - mkdir docs/edgy-joke
  - mkdir docs/how-i-got-here
  # Generate reveal.js powered HTML from Markdown
  - pandoc --standalone -t revealjs -o docs/edgy-joke/index.html edgy-joke/slides.md -V revealjs-url=https://unpkg.com/reveal.js@^4/ -V theme=solarized
  - pandoc  --standalone -t revealjs  -o docs/how-i-got-here/index.html how-i-got-here/slides.md -V revealjs-url=https://unpkg.com/reveal.js@^4/ -V theme=dracula

# Deploy to GitHub pages (see https://docs.travis-ci.com/user/deployment/pages/)
deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
